### ISSUE TITLE
Support Wildfly 14 container (EE8 Certified)

### ISSUE THREAD

**Issue by mark1900** [arquillian/arquillian-container-chameleon#115]
##### Issue Overview

Currently, there is only support for Wildfly up to version 13. Versions 14 is EE8 Certified.

##### Additional Information

- http://wildfly.org/news/2018/08/30/WildFly14-Final-Released/
- Support Wildfly 12,13 containers - #91

**Comment by yntelectual** [comment]
hi any plans to make a new release? last version is still RC4...

**Comment by bartoszmajsak** [comment]
> hi any plans to make a new release? last version is still RC4...

Sure, I will take care of #127 and cut the release this week

**Comment by bartoszmajsak** [comment]
Provided by #128
