### ISSUE TITLE
ArquillianChameleon.addsArquillianFile throws AbstractMethodError in Java 11

### ISSUE THREAD

**Issue by kunapulir** [arquillian/arquillian-container-chameleon#138]
ArquillianChameleon class makes a hard assumption that the class loader that loads the test class will be a URLClassLoader. While this may have worked until Java 8, starting from Java 9, built-in class loader hierarchy has changed. In Java 11, for instance, the class loader is of type AppClassLoader.

**Comment by bartoszmajsak** [comment]
Hi @kunapulir 

Many thanks for reporting it. Would you be up for helping us out fixing it by submitting a PR?
