### ISSUE TITLE
chameleonContainerConfigurationFile property needs to be prefixed by slash

### ISSUE THREAD

**Issue by rmpestano** [arquillian/arquillian-container-chameleon#16]
when I use chameleonContainerConfigurationFile property in arquillian.xml to provide custom containers to chameleon I've got
``` java.lang.IllegalStateException: 
Could not setup chameleon container
at org.arquillian.container.chameleon.ChameleonContainer.init(ChameleonContainer.java:55)
...
 Caused by: org.yaml.snakeyaml.error.YAMLException: java.io.IOException: Stream closed
```

here is arquillian.xml
```
<container qualifier="chameleon" default="true">
		<configuration>
			<property name="chameleonTarget">jboss:6.3.4.Final:${arquillian.containerMode}</property>
			<property name="chameleonContainerConfigurationFile">containers.yaml</property>
		</configuration>
	</container>
```

containers.yaml is in src/test/resources folder

When I use **/containers.yaml** everything works.

**Comment by aslakknutsen** [comment]
Ah yes, It's being read as a ClassLoader resource.. Should probably do something similar to Core where we attempt CL then File is not found etc.. 

https://github.com/arquillian/arquillian-container-chameleon/blob/master/src/main/java/org/arquillian/container/chameleon/ContainerLoader.java#L19

Pull Request welcome :)
