### ISSUE TITLE
Load chameleon configuration from jar

### ISSUE THREAD

**Issue by rmpestano** [arquillian/arquillian-container-chameleon#40]
Hi there,

here at the company we use a custom container based on eap 6.4. To make it work we need to provide our **containers.yaml** in chameleon/default folder. This repeats for every project at the company.

There is a way to provide custom chameleon.yaml as a dependency on classpath?

ps: didn't tested that so just asking and if not I could try to contribute if you think its interesting.

**Comment by aslakknutsen** [comment]
You can. The default configuration file is loaded via Classloader resources.

Just provide the ClassLoader resource 'path' instead of a File path and it should be loaded.

https://github.com/arquillian/arquillian-container-chameleon/blob/master/src/main/java/org/arquillian/container/chameleon/FileUtils.java

**Comment by aslakknutsen** [comment]
What custom modifications did you need to do?

**Comment by rmpestano** [comment]
great, I see loadClassPathResource, I think it will work then.

For our custom EAP(6.4) I think we have modules (a lot of them) and also patches(f12rom redhat). I think the patches are the official ones.

**Comment by rmpestano** [comment]
will test tomorrow and will come back here to confirm. thanks!

**Comment by rmpestano** [comment]
Hi Aslak,
Could not make It work, here is the jar contents I have in my test classpath:

![chameleon-classpath](https://cloud.githubusercontent.com/assets/1592273/13250543/527f4cda-da09-11e5-8f4a-7612b0ab2d23.png)

but Arquillian is not finding my custom container:

````
Caused by: java.lang.IllegalArgumentException: No container configuration found in null for target jboss-procergs:6.3.4.Final:remote

````

I have just changed **gav** in this custom container so chameleon can download our jboss distribution. 

It would be nice if we could parametrize gav because its a bit overkill to provide a *containers.yaml* which just have different gav. In my case I still relaying in *org.jboss.as:jboss-as-arquillian-container-remote:7.2.0.Final* adapter.

**Comment by aslakknutsen** [comment]
You're trying to override the default file here, so you need to ensure that this artifact is placed before the chameleon jar on the classpath. Or you could create a file with your own name and configure the 'chameleonContainerConfigurationFile'.

We could open up for an 'override' built in profiles options. Something like:

```yaml
override: jboss eap:6.4:managed
  dist:
    gav: custom
``` 

Then merge that into a single profile internally.

**Comment by rmpestano** [comment]
I've tried chameleonContainerConfigurationFile but without success:

````
   <property name="chameleonContainerConfigurationFile">procergs.yaml</property>
````

  here's exception: 

````
Caused by: org.jboss.arquillian.container.spi.ConfigurationException: Could not locate configured containerConfigurationFile as file nor classloader resource: procergs.yaml
	at org.arquillian.container.chameleon.FileUtils.loadConfiguration(FileUtils.java:43)
````
Looking at FileUtils it should work, here is my jar file:

![chameleon-classpath](https://cloud.githubusercontent.com/assets/1592273/13251819/2ca2f3a6-da11-11e5-8dbb-f80c8b1d901b.png)

**Comment by rmpestano** [comment]
Ahh my bad, looking at my comment I could find the issue, yaml file must be in resources.

Now its ok, thank you very much. Closing the issue.
