### ISSUE TITLE
Support Domain mode of WildFly and EAP servers

### ISSUE THREAD

**Issue by mgencur** [arquillian/arquillian-container-chameleon#43]

**Comment by mgencur** [comment]
PR: https://github.com/arquillian/arquillian-container-chameleon/pull/44

**Comment by MatousJobanek** [comment]
PR merged and landed in https://github.com/arquillian/arquillian-container-chameleon/commit/296dc1609fc54eaa4947b2f9dd1c82ced4452b8d
