### ISSUE TITLE
How to customize wildfly before running test?

### ISSUE THREAD

**Issue by ducva** [arquillian/arquillian-container-chameleon#45]
Sorry for dummy question. but

I need to deploy postgres driver to wildfly (managed) before running my test.

How can I do that with chameleon?

**Comment by bartoszmajsak** [comment]
Could you please move this question to our forum [discuss.arquillian.org/](http:discuss.arquillian.org/)?
I will be happy to answer right away. 

Purpose of GitHub issues is a bit different :) Thanks for your understanding.
