### ISSUE TITLE
investigate how to provide resolution for arbitrary container

### ISSUE THREAD

**Issue by smiklosovic** [arquillian/arquillian-container-chameleon#6]
I guess we should not leave Android containers behind. I know it is pretty specific but Droidium provides the first class container itself so why not to support that really ...

**Comment by aslakknutsen** [comment]
You're talking about going beyond just JBoss AS / EAP / WildFly here?

**Comment by smiklosovic** [comment]
basically yes, how is tomcat / glassfish / android / whatever container different from jbosses? they are all containers in the end as jbosses are and you can do that maven resolution as well

**Comment by aslakknutsen** [comment]
@smiklosovic true, the main difference is they don't have 3 different group/artifact ids and very specific version combinations based on which server version you're attempting to target :)

But yeah, technically no reason we couldn't include more containers. Just need to complete the Profile SPI and have some kinda configuration loading..

**Comment by gpoul** [comment]
Just saw the alpha announcement and I would be very interested in also supporting WebSphere Liberty Profile!

**Comment by rmpestano** [comment]
Hi there, couldnt we have a "container catalog" for that? like jboss forge does with its plugins:
https://github.com/forge/plugin-repository/blob/master/repository.yaml

something like this:

name: jboss-eap
version: 6.2
maven-coordinates:  org.jboss:jboss-eap-dist
folder-name: jboss-eap-dist-6.3.3.Final  //stands for outputDirectory after unzip
description: ...
whatElseNeededToDownloadAndRun

Also here at the company we have our own EAP (zip) distribution distribution so it would be nice if the app could provide its "catalog" or whatever so that chameleon can download and extract custom containers. WDYT?

**Comment by smiklosovic** [comment]
@rmpestano yes, that would very nice, i have no complaints whatoever and I am all hands for it. The question is who is going to implement that :)

**Comment by rmpestano** [comment]
Just to clarify, the idea of a central catalog is just to easy the contribution, like e.g: WAS liberty would send a PR with their catalog entry.

**Comment by aslakknutsen** [comment]
@rmpestano Yeah, that's been the idea for longer then I dare to remember. The plan was to auto generate the catalog based on data from arquillian.org. 

The same data is needed by Forge and JBoss Tools. The Forge Arquillian plugin has a semi catalog today but it's missing some of the 'expressions' needed for this. 

https://github.com/forge/addon-arquillian/blob/master/src/main/resources/containers.json

We can clone this one and start modifying it as we need.

**Comment by lfryc** [comment]
We still have to provide local version of the catalogue, perhaps baked into the release version so that Chameleon works offline.

**Comment by aslakknutsen** [comment]
:+1:

**Comment by aslakknutsen** [comment]
Perhaps something like:

```json
[
	{
		"server": "wildfly",
		"version_expression": "8.*",
		"adapter": [
			{
				"type": "remote",
				"gav": "org.wildfly:wildfly-arquillian-container-remote:${version}",
				"class": "org.jboss.as.arquillian.container.remote.RemoteDeployableContainer",
				"dependencies": [
				],
			},
			{
				"type": "managed",
				"gav": "org.wildfly:wildfly-arquillian-container-managed:${version}",
				"class": "org.jboss.as.arquillian.container.remote.ManagedDeployableContainer",
				"dependencies": [
				],
				"configuration": {
					"jbossHome": "${dist}"
				}
			},
			{
				"type": "embedded",
				"gav": "org.wildfly:wildfly-arquillian-container-embedded:${version}",
				"class": "org.jboss.as.arquillian.container.remote.EmbeddedDeployableContainer",
				"dependencies": [
				],
				"configuration": {
					"jbossHome": "${dist}"
				}
			}
		],
		"dist": {
			"gav": "org.wildfly:wildfly-dist:zip:${version}"
		},
		"exlude": [
        		"org.jboss.arquillian.test:*",
                "org.jboss.arquillian.testenricher:*",
                "org.jboss.arquillian.container:*",
                "org.jboss.arquillian.core:*",
                "org.jboss.arquillian.config:*",
                "org.jboss.arquillian.protocol:*",
                "org.jboss.shrinkwrap.api:*",
                "org.jboss.shrinkwrap:*",
                "org.jboss.shrinkwrap.descriptors:*",
                "org.jboss.shrinkwrap.resolver:*",

                "*:wildfly-arquillian-testenricher-msc",
                "*:wildfly-arquillian-protocol-jmx",

                "*:jboss-as-arquillian-testenricher-msc",
                "*:jboss-as-arquillian-protocol-jmx"			
		]
	},
	{
		"server": "wildfly",
		"version_expression": "9.*",
		"adapter": [
			{
				"type": "remote",
				"gav": "org.wildfly.arquillian:wildfly-arquillian-container-remote:1.0.0.Alpha5",
				"class": "org.jboss.as.arquillian.container.remote.RemoteDeployableContainer",
				"dependencies": [
				],
			},
			{
				"type": "managed",
				"gav": "org.wildfly.arquillian:wildfly-arquillian-container-managed:1.0.0.Alpha5",
				"class": "org.jboss.as.arquillian.container.remote.ManagedDeployableContainer",
				"dependencies": [
				],
				"configuration": {
					"jbossHome": "${dist}"
				}
			},
			{
				"type": "embedded",
				"gav": "org.wildfly.arquillian:wildfly-arquillian-container-embedded:1.0.0.Alpha5",
				"class": "org.jboss.as.arquillian.container.remote.EmbeddedDeployableContainer",
				"dependencies": [
				],
				"configuration": {
					"jbossHome": "${dist}"
				}
			}
		],
		"dist": {
			"gav": "org.wildfly:wildfly-dist:zip:${version}"
		},
		"exlude": [
        		"org.jboss.arquillian.test:*",
                "org.jboss.arquillian.testenricher:*",
                "org.jboss.arquillian.container:*",
                "org.jboss.arquillian.core:*",
                "org.jboss.arquillian.config:*",
                "org.jboss.arquillian.protocol:*",
                "org.jboss.shrinkwrap.api:*",
                "org.jboss.shrinkwrap:*",
                "org.jboss.shrinkwrap.descriptors:*",
                "org.jboss.shrinkwrap.resolver:*",

                "*:wildfly-arquillian-testenricher-msc",
                "*:wildfly-arquillian-protocol-jmx",

                "*:jboss-as-arquillian-testenricher-msc",
                "*:jboss-as-arquillian-protocol-jmx"			
		]
	}
]
```
