### ISSUE TITLE
Provide API to check given container is supported by chameleon or not

### ISSUE THREAD

**Issue by dipak-pawar** [arquillian/arquillian-container-chameleon#65]
##### Issue Overview
Currently we don't have api to check given container is supported by chameleon or not.

Implement a method which will give you boolean value depending on container is supported or not.
```java
public static boolean isSupported(String source) {}
```

**Comment by bartoszmajsak** [comment]
Keep in mind that some containers are defined using Maven `g:a:v` but others are defined using `URL`s, so querying for `dist` is not the way to go. We can try to re-use the logic which chameleon uses on its own when you specify which container has to be installed.

**Comment by dipak-pawar** [comment]
@bartoszmajsak  Thanks for informing me about `URL`S.

Can you give me one example who is defining using URL? So I will get detailed idea about it.

**Comment by bartoszmajsak** [comment]
It's in the same `yaml` file - for example Tomcat container.
