### ISSUE TITLE
Support JDK9+

### ISSUE THREAD

**Issue by papegaaij** [arquillian/arquillian-container-chameleon#90]
`arquillian-container-chameleon` does not work on JDK9+ due to a failure locating `java.sql.Date` from snakeyaml. This issue was first reported 2 years ago at http://lists.jboss.org/pipermail/wildfly-dev/2016-July/005249.html . It can also be observed by building the source code with OpenJDK 10.

To get arquillian-container-chameleon build on OpenJDK 10 I had to upgrade the `jboss-parent` to 26. To fix the classloader issue, apply the following patch:

```
--- a/arquillian-chameleon-extension/src/main/java/org/arquillian/container/chameleon/ContainerLoader.java
+++ b/arquillian-chameleon-extension/src/main/java/org/arquillian/container/chameleon/ContainerLoader.java
@@ -35,7 +35,7 @@ public class ContainerLoader extends Loader {
 
         File[] archives = Resolver.resolve(cacheFolder, mavenDependencies);
 
-        ClassLoader classloader = new URLClassLoader(Utils.toURLs(archives), null);
+        ClassLoader classloader = new URLClassLoader(Utils.toURLs(archives), ClassLoader.getPlatformClassLoader());
         return loadContainers(classloader, containers);
     }
 }
```

A complicating factor is that many of the containers currently supported do not run on JDK9+ (such as WildFly 9).

**Comment by Tibor17** [comment]
@papegaaij 
@bartoszmajsak 
We fixed the same ClassLoading issue in ASF - Surefire Maven.
This requires a little bit more reflection and recognize Java Version.
If the fix is so simple please release a new version. Thx.
